export const repos = [
  // {
  //   name: "fnly",
  //   description: "Develop and deploy your functions",
  //   repo: "https://github.com/shamilkotta/fnly",
  //   homepage: "",
  //   full_name: "github/fnly",
  //   isLive: false,
  //   isDraft: true,
  // },
  {
    name: "dotlet",
    description: "Make your environment portable",
    repo: "https://github.com/shamilkotta/dotlet",
    homepage: "https://dotlet.app",
    full_name: "github/dotlet",
    isLive: true,
    isDraft: true,
  },
  {
    name: "nlite",
    description: "A attempt to create a lite react 19 framework using vite",
    repo: "https://github.com/shamilkotta/nlite",
    homepage: "",
    full_name: "github/nlite",
    isLive: false,
    isDraft: true,
  },
  {
    name: "git-sync",
    description:
      "Obsidian plugin for syncing the vault with git & github for both desktop and mobile",
    repo: "https://github.com/shamilkotta/git-sync",
    homepage: "",
    full_name: "github/git-sync",
    isLive: true,
    isDraft: false,
  },
  {
    name: "rlist",
    description: "Your digital library, simplified",
    repo: "https://github.com/shamilkotta/rlist",
    homepage: "https://rlist.app",
    full_name: "github/rlist",
    isLive: true,
    isDraft: true,
  },
  {
    name: "journeygrid",
    description: "Journal your journey",
    repo: "https://github.com/shamilkotta/journeygrid",
    homepage: "https://journeygrid.vercel.app",
    full_name: "github/journeygrid",
    isLive: true,
    isDraft: false,
  },
  {
    name: "zshi",
    description: "A light intelligence in your zsh",
    repo: "https://github.com/shamilkotta/zshi",
    homepage: "https://www.npmjs.com/package/zshi",
    full_name: "github/zshi",
    isLive: true,
    isDraft: false,
  },
  {
    name: "rn-drag-resize",
    description:
      "Draggable and Resizable component using React Native Reanimated",
    repo: "https://github.com/shamilkotta/rn-drag-resize",
    homepage: "https://www.npmjs.com/package/@shamilkotta/rn-drag-resize",
    full_name: "github/rn-drag-resize",
    isLive: true,
    isDraft: false,
  },
  {
    name: "quick-switch",
    description: "A quick tab search extension for Chrome",
    repo: "https://github.com/shamilkotta/quick-switch",
    homepage: null,
    full_name: "github/quick-switch",
    isLive: false,
    isDraft: false,
  },
  {
    name: "clone-ai",
    description: "A minimal ai chat app to talk with multiple models",
    repo: "https://github.com/shamilkotta/clone-ai",
    homepage: "https://a-clone-ai.vercel.app/",
    full_name: "github/clone-ai",
    isLive: true,
    isDraft: true,
  },
  {
    name: "shamilkotta",
    description:
      "SDE | Full stack Web & Mobile Developer | Typescript Enthusiast",
    repo: "https://github.com/shamilkotta/shamilkotta",
    homepage: "https://shamilkotta.github.io",
    full_name: "github/shamilkotta",
    isLive: true,
    isDraft: false,
  },
  // {
  //   name: "github-readme-streak-stats",
  //   description: null,
  //   repo: "https://github.com/shamilkotta/github-readme-streak-stats",
  //   homepage: "https://github-readme-streak-stats-drab-six.vercel.app",
  //   full_name: "github/github-readme-streak-stats",
  //   isLive: false,
  //   isDraft: false,
  // },
  // {
  //   name: "gitActions",
  //   description: "A repository created for learning github actions",
  //   repo: "https://github.com/shamilkotta/gitActions",
  //   homepage: "",
  //   full_name: "github/gitActions",
  //   isLive: false,
  //   isDraft: false,
  // },
  // {
  //   name: "github-stats",
  //   description: ":zap: Dynamically generated stats for your github readmes",
  //   repo: "https://github.com/shamilkotta/github-stats",
  //   homepage: "https://shamilkotta-github-stats.vercel.app",
  //   full_name: "github/github-stats",
  //   isLive: true,
  //   isDraft: false,
  // },
  // {
  //   name: "React_Webpack",
  //   description: "Created a react app from scratch using Webpack and Babel",
  //   repo: "https://github.com/shamilkotta/React_Webpack",
  //   homepage: "",
  //   full_name: "github/React_Webpack",
  //   isLive: false,
  //   isDraft: true,
  // },
  // {
  //   name: "simple-rsc",
  //   description:
  //     "A simple React Server Components implementation that you can build yourself 🙌",
  //   repo: "https://github.com/shamilkotta/simple-rsc",
  //   homepage: "https://www.youtube.com/watch?v=Fctw7WjmxpU",
  //   full_name: "github/simple-rsc",
  //   isLive: false,
  //   isDraft: false,
  // },
  // {
  //   name: "awesome-github-profiles",
  //   description:
  //     "List of GitHub profiles that have awesome customisation, that you can use for inspiration",
  //   repo: "https://github.com/shamilkotta/awesome-github-profiles",
  //   homepage: "https://eddiehubcommunity.github.io/awesome-github-profiles/",
  //   full_name: "github/awesome-github-profiles",
  //   isLive: false,
  //   isDraft: false,
  // },
  // {
  //   name: "wemakedevs",
  //   description: "Inspire. Educate. Empower.",
  //   repo: "https://github.com/shamilkotta/wemakedevs",
  //   homepage: "https://wemakedevs.org",
  //   full_name: "github/wemakedevs",
  //   isLive: false,
  //   isDraft: false,
  // },
  // {
  //   name: "UpBit_FrontEnd",
  //   description:
  //     "UpBit is website for freelancing Developers, you can also create your products with collaborating with developers.",
  //   repo: "https://github.com/shamilkotta/UpBit_FrontEnd",
  //   homepage: "",
  //   full_name: "github/UpBit_FrontEnd",
  //   isLive: false,
  //   isDraft: false,
  // },
  // {
  //   name: "UpBit_BackEnd",
  //   description:
  //     "UpBit is website for freelancing Developers, you can also create your products with collaborating with developers..!",
  //   repo: "https://github.com/shamilkotta/UpBit_BackEnd",
  //   homepage: "",
  //   full_name: "github/UpBit_BackEnd",
  //   isLive: false,
  //   isDraft: false,
  // },
  // {
  //   name: "edWorld",
  //   description:
  //     "A student and teacher management app for educational institutions, Build on Nodejs, Mongodb and handlebars with bootstrap5",
  //   repo: "https://github.com/shamilkotta/edWorld",
  //   homepage: "https://edworld.onrender.com",
  //   full_name: "github/edWorld",
  //   isLive: true,
  //   isDraft: false,
  // },
  // {
  //   name: "express-sample-2",
  //   description: null,
  //   repo: "https://github.com/shamilkotta/express-sample-2",
  //   homepage: null,
  //   full_name: "github/express-sample-2",
  //   isLive: false,
  //   isDraft: false,
  // },
];
